### ISSUE TITLE
SIP NAT configuration

### ISSUE THREAD

**Issue by fholzhauser** [jamhed/kazoo-docker#12] opened 2017-03-31 08:21 UTC
Thanks for working on these docker images! It makes it really easy to have everything installed, very useful. 

I'm running the minimal images on a PC for testing/experimenting purposes. I have problems with calls getting disconnected after 30 sec, due to ACK timeout, and also with not having voice. 
I believe that the cause of these issues is that the docker setup implies the scenario of having kazoo behind NAT. Kamailio and Freeswitch however do not seem to be configured for this in the images. In the traces I see that the adresses/ports of the kazoo docker network bridge are communicated to the clients on SIP/SDP. This is a problem e.g. when clients want to send an ACK after receiving a 200 OK with the Freeswitch IP/Port in the SIP contact header. 

Would it be possible to have Kamailio/Freeswitch configured by default for this "behind NAT" scenario to modify the relevant SIP headers and communicate the RTP endpoints with a "public" IP? Or is this already taken care of and I have missed something completely obvious ?

**Comment by jamhed** [comment] 2017-03-31 17:33
Well, it seems it requires some tweaking to make it work as intended. Thanks for the report, I'll take a peek and let you know.

**Comment by fholzhauser** [comment] 2017-04-03 08:15
Thanks. I'll try to figure out those tweaks as well and keep you posted. Probably you'll beat me to it though as I'm not mastering Kamailio (yet).

**Comment by jamhed** [comment] 2017-04-03 21:20
@fholzhauser, please update to latest: remove all kazoo images from docker host, and run run.sh again, I've added something.

**Comment by jamhed** [comment] 2017-04-03 21:28
See https://github.com/jamhed/kazoo-docker#networking as brief explanation.

**Comment by fholzhauser** [comment] 2017-04-04 10:10
Thanks for the update. 

I have noticed that now kamailio only starts with the run script. When trying to start it with the start script it fails with :
```
0(1) : <core> [core/cfg.y:3407]: yyerror_at(): parse error in config file /usr/local/kamailio/etc/kamailio/local.cfg, line 121, column 59-67: syntax error
0(1) : <core> [core/cfg.y:3407]: yyerror_at(): parse error in config file /usr/local/kamailio/etc/kamailio/local.cfg, line 121, column 59-67: 
```
Probably it has something to do with the EXT_IP environment not being present during normal start.

Regarding the calls, I still have disconnections after 30 sec, but it might be some other issue. I'll dig into it and see whether it is related or not.

In the mean time I experimented with simply replacing the IP:Port (with subst) in the contact headers going out in the relevant routing paths (). It actually works, but probably you had a good reason not to go that way, so I'll stick to your solution.

**Comment by jamhed** [comment] 2017-04-04 10:13
> Regarding the calls, I still have disconnections after 30 sec

This is definitely related with sip messages not being passed either to phone, or to Kazoo's freeswitch.

What is your setup? This works on Scaleway: Docker host with no external ip.

**Comment by jamhed** [comment] 2017-04-04 10:14
> I experimented with simply replacing the IP:Port

By the way, how do you do that? AFAIK it's not that easy in Kazoo.

**Comment by jamhed** [comment] 2017-04-04 10:38
> I have noticed that now kamailio only starts with the run script.

You probably need to re-install docker image (e.g. remove old one with docker rmi).

**Comment by fholzhauser** [comment] 2017-04-14 13:59
Sorry for the late reply.
With the latest images, calls work fine, thanks. FYI : previously I changed the contact header in the messages sent out using subst in the relevant routing rules in default.cfg of kamailio. Since the new config of yours works, I don't do that anymore.

Regarding the start problem I guess it is caused by the EXT_IP environment being present at subsequent starts of the kamailio container after run. What fixed it for me is to change the sed line in config-local.sh to replace the whole line (not only the "listen=UDP_SIP" text) when adding the advertise bit to local.cfg.

**Comment by jamhed** [comment] 2017-04-19 20:37
Yep, fixed last one. I suppose we can close this now.

**Closed as completed by jamhed** 2017-04-19 20:37 UTC

**Comment by fholzhauser** [comment] 2017-04-20 12:21
Indeed, thanks for the fix !
